name: Build and Upload Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 构建步骤（示例：生成一个文件）
      - name: Generate artifact
        run: echo "Hello, Artifact!" > output.txt

      # 3. 上传 Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output.txt
          # path 也支持通配符（如 'dist/**' 或 '*.log'）
