name: gancc

on:
  push:
    branches: [main]

jobs:
  access-other-repo:
    runs-on: [ubuntu-latest]  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Private Repo
        env:
          PAT: ${{ secrets.MY_ACCESS_TOKEN }}
        run: | 
          home/runner/.docker/config.json
